// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv3EX68kMdoBImg_ajL499sSyRF_8Jnic',
    appId: '1:1029614245585:web:5165d1f8ca266dbeff97f0',
    messagingSenderId: '1029614245585',
    projectId: 'revmaster-3e9df',
    authDomain: 'revmaster-3e9df.firebaseapp.com',
    databaseURL: 'https://revmaster-3e9df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'revmaster-3e9df.appspot.com',
    measurementId: 'G-3GJ4JKZQCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF5m5lr7xRI-LnZ6By0RCJNp-GHkz-P6M',
    appId: '1:1029614245585:android:df1839ce5d368410ff97f0',
    messagingSenderId: '1029614245585',
    projectId: 'revmaster-3e9df',
    databaseURL: 'https://revmaster-3e9df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'revmaster-3e9df.appspot.com',
  );
}
