name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.0  

      - name: Install dependencies
        run: flutter pub get
        working-directory: mobile

      # - name: Analyze project source
      #   run: flutter analyze
      #   working-directory: mobile_app

      - name: Run tests
        run: flutter test
        working-directory: mobile
