name: Flutter CI

on:
  push:
    branches: [ "main" ] # Replace "main" with your branch name
  pull_request:
    branches: [ "main" ] # Replace "main" with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.0  # or a specific version of Flutter

      - name: Install dependencies
        run: flutter pub get
        working-directory: mobile_app

      - name: Analyze project source
        run: flutter analyze
        working-directory: mobile_app

      # - name: Run tests
      #   run: flutter test
      #   working-directory: mobile_app
